#!/bin/bash
set +e

docker rm -f camera0 camera1 camera2 camera3

VERSION=0.2
docker run -d --name camera0 --restart=always --ip 192.168.1.200 --mac-address e8:94:f6:02:56:58 --network hostnic mendonca/mockup-camera:$VERSION ./camera
docker run -d --name camera1 --restart=always --ip 192.168.1.201 --mac-address e8:94:f6:02:37:6c --network hostnic mendonca/mockup-camera:$VERSION ./camera
docker run -d --name camera2 --restart=always --ip 192.168.1.202 --mac-address c0:4a:00:04:e7:80 --network hostnic mendonca/mockup-camera:$VERSION ./camera
docker run -d --name camera3 --restart=always --ip 192.168.1.203 --mac-address 90:f6:52:05:fe:5d --network hostnic mendonca/mockup-camera:$VERSION ./camera